### ISSUE TITLE
Could not load file or assembly Microsoft.CodeAnalysis

### ISSUE THREAD

**Issue by randalvance** [cezarypiatek/CSharpExtensions#14]
Hi Cezary,

We are unable to make this work even for a brand new C# console project. We are currently receiving the following error.

```
 An instance of analyzer CSharpExtensions.Analyzers3.NotNullablePropertyInitializationDiagnosticSuppressor cannot be created from C:\Users\racu\.nuget\packages\smartanalyzers.csharpextensions.annotations\2.5.65\analyzers\dotnet\cs\CSharpExtensions.Analyzers3.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
```

The non-nullable properties are still being marked with a warning and we suspect it is of the error above.

![image](https://user-images.githubusercontent.com/3318476/92080681-822cd200-edf4-11ea-9508-54c512ffb8ea.png)

Note:
We are able to build the project with `dotnet build` without any problems. 

We also tried installing `Microsoft.CodeAnalysis` version `3.5.0.0` to the project but we are still receiving the error.

Do you have any ideas on how to resolve this issue?

Thank you.

**Comment by randalvance** [comment]
Hi @cezarypiatek,

Initially, I experience this in all Visual Studio 2019, Visual Studio Code, and Rider. After updating Visual Studio 2019 to latest version (16.7.2), it fixed the issue for it. I still encounter the issue in Visual Studio Code with latest Omnisharp, and in Rider with it's latest 2020.2.1 version.

**Comment by cezarypiatek** [comment]
What's the ``TargetFramework` of your project?

**Comment by randalvance** [comment]
Hi @cezarypiatek ,

Tried this in
`netstandard2.0`
`net472`

And installed .net core sdk. We tried it for both
`.NET Core 3.1.401`
`.NET 5 Preview 8`

**Comment by cezarypiatek** [comment]
I ask my colleague who is using Rider about it and he didn't encounter such a problem. I've also tested it by myself on Rider 2020.2.1 and everything looks good.  Looking at StarckOVerflow it seems to be a transitive problem with the hosting IDE https://stackoverflow.com/questions/42536506/could-not-load-file-or-assembly-microsoft-codeanalysis-version-1-3-1-0-cultu I'm sorry but there's nothing I can do about it. Maybe `.NET 5 Preview 8` is causing this problem? You can also try to clean up your temporary directory

**Comment by randalvance** [comment]
Hi @cezarypiatek,

Note that this is also replicable in the latest stable version of .NET Core (`3.1.401`). I even tried it on my Mac with same Rider version, deleted the `.nuget` folder as well, but still the same problem.

I've created a simple demo project to demonstrate it.
https://github.com/randalvance/CSharpAnalyzerBugDemo

May I know what specific version of .NET SDK you are using?

Thank you.

**Comment by randalvance** [comment]
I opened a separate issue in Jetbrains.
https://youtrack.jetbrains.com/issue/RIDER-50473

**Comment by cezarypiatek** [comment]
Thanks, I will keep track of that issue. Btw, really good description 👍

**Comment by randalvance** [comment]
Hi @cezarypiatek,

I discovered that Visual Studio 2019 16.7.2 also has a problem.

The DiagnosticSuppressor work in VS2019, but no errors are marked if I don't initialize the properties in the property initializer.

![image](https://user-images.githubusercontent.com/3318476/92425447-de5b7180-f1b9-11ea-8e28-7e49964d9214.png)

This is how it looks in Resharper.

![image](https://user-images.githubusercontent.com/3318476/92425441-dac7ea80-f1b9-11ea-97e9-1d3e6bf5550e.png)

**Comment by cezarypiatek** [comment]
This is what I've got from VisualStudio 16.7.2  + R# 2020.2

![image](https://user-images.githubusercontent.com/7759991/92991177-44116b80-f4e2-11ea-994d-2b16dfefba47.png)


It looks like R# has own analyzer related to the nullable types and it's not supporting Roslyn suppressor but there's an option to disable it:

![image](https://user-images.githubusercontent.com/7759991/92991201-77ec9100-f4e2-11ea-93d8-a31857983b2d.png)

The same option should be available in the Rider

![image](https://user-images.githubusercontent.com/7759991/92991296-4a541780-f4e3-11ea-97ae-33303b7e1856.png)


I have no idea why your VS is not reporting `CSE001` - probably this is caused by your local setup (maybe the installation is corrupted).

On my machine is working correctly with VS, RIder and don't CLI

![image](https://user-images.githubusercontent.com/7759991/92991369-acad1800-f4e3-11ea-8e5d-e8cf416a8065.png)


I really would like to help you but I can't reproduce this issue.
