### ISSUE TITLE
CS8600 doesn't show up anymore

### ISSUE THREAD

**Issue by jmevel** [cezarypiatek/CSharpExtensions#40]
Hello,

When using the `SmartAnalyzers.CSharpExtensions.Annotations` (3.9.0) Nuget package, the `CS8600: Converting null literal or possible null value to non-nullable type.` warning doesn't show up anymore even if `InitRequiredForNotNullAttribute` is activated

```csharp
class Person
{
    public string Name { get; set; }
}

Person foo = new Person { Name = null };
foo = null;
foo.Name = null;
```

Expected: CS8600 warning at each of the 3 lines above
Result: no warning at all

I think this warning should be kept no matter if `InitRequiredForNotNullAttribute` is activated or not. Otherwise we incur a risk of assigning null to a non-nullable reference type.

**Comment by cezarypiatek** [comment]
Hi @jmevel,

Thanks for reporting this issue. However, this must be caused by some other factors.  `CSharpExtensions` package has nothing to do with `CS8600` as it provides suppressor only for `CS8618`  which is a totally different diagnostic. Please review all your `.editorconfig` or ruleset files and make sure that `CS8600` has the expected severity and non-nullable references are enabled.

**Comment by jmevel** [comment]
Hi @cezarypiatek,

You were right, my bad. 
I simply forgot to activate the Nullable Reference Types feature in one of my project in my solution.
Sorry for opening a ticket too quickly. I ensured your Nuget package was installed in my project and that `InitRequiredForNotNullAttribute` was activated so I just assumed NRT was of course enabled... which wasn't actually.

Thanks for your answer!

**Comment by cezarypiatek** [comment]
No worries, I'm glad that I could help.
